#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit
[[ -n "${VERBOSE:-}" ]] && set -o verbose
[[ -n "${DEBUG:-}" ]] && IS_DEBUG=true || IS_DEBUG=false

readonly SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
# shellcheck source=./init.bash
source "$SCRIPT_DIR"/init.bash

result=$(l.ask hello)
echo "${result}"

if [[ $result == YES ]]; then
  echo "# do something if YES"
else
  echo "# do something if NO"
fi
