#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

readonly SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
# shellcheck source=./init.bash
source "$SCRIPT_DIR"/init.bash

result=$(l.ask_with_cancel 'ask with default value Yes' Y)
echo "result=$result"

if [[ $result == CANCEL ]]; then
  echo "# do something if CANCEL"
else
  if [[ $result == YES ]]; then
    echo "# do something if YES"
  else
    echo "# do something if NO"
  fi
fi
result=$(l.ask 'ask without default value')
echo "result=$result"
