#!/usr/bin/env bash
# shellcheck disable=SC2119

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
readonly SCRIPT_DIR
# shellcheck source=./init.bash
source "$SCRIPT_DIR"/init.bash

# It is same to wc -l
printf 'a' | l.count_lines.p
printf 'a\n' | l.count_lines.p
printf 'a\nb' | l.count_lines.p
printf 'a\nb\n' | l.count_lines.p
printf 'a\nb\n\n' | l.count_lines.p
