#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit
[[ -n "${VERBOSE:-}" ]] && set -o verbose

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
readonly SCRIPT_DIR
# shellcheck source=./init.bash
source "$SCRIPT_DIR"/init.bash

before=(B a C d E b 8 1 2 4)
readarray -t after < <(l.sort before)
echo "Before size: ${#before[@]}"
echo "Before: ${before[*]}"
echo "After size: ${#after[@]}"
echo "After: ${after[*]}"
