#!/usr/bin/env bash
# shellcheck disable=SC2119

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit
[[ -n "${VERBOSE:-}" ]] && set -o verbose

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
readonly SCRIPT_DIR
# shellcheck source=./init.bash
source "$SCRIPT_DIR"/init.bash

l.trace_start
echo '  123  ' | l.trim
l.trace_end

l.trace_start 1 lv-1
l.trim ' abc '
l.trace_end

l.trace_start 2 lv-2
l.trim ' abc '
l.trace_end

l.trace_start 3 lv-3
l.trim ' abc '
l.trace_end
