#!/usr/bin/env bash
# shellcheck disable=SC1090

set -o errexit
set -o nounset
set -o pipefail
shopt -s inherit_errexit
[[ -n "${VERBOSE:+x}" ]] && set -o verbose
[[ -n "${DEBUG:-}" ]] && IS_DEBUG=true || IS_DEBUG=false

readonly SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
source "$SCRIPT_DIR"/init.bash

l.trace_start
echo '  123  ' | l.trim
l.trace_end

l.trace_start 1 lv-1
l.trim ' abc '
l.trace_end

l.trace_start 2 lv-2
l.trim ' abc '
l.trace_end

l.trace_start 3 lv-3
l.trim ' abc '
l.trace_end
