#!/usr/bin/env bash
# shellcheck disable=SC1090

set -o errexit
set -o nounset
set -o pipefail
shopt -s inherit_errexit
[[ -n "${VERBOSE:+x}" ]] && set -o verbose
[[ -n "${DEBUG:-}" ]] && IS_DEBUG=true || IS_DEBUG=false

readonly SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
source "$SCRIPT_DIR"/init.bash

foo() {
  l.trace_stack foo
}

# It will print:
# Trace Function Stack:
#   # Function (File:Line)
#   - main (./example/trace:0)
l.trace_stack

# It will print:
# Trace Function Stack: foo
#   # Function (File:Line)
#   - foo (./example/trace:36)
#   - main (./example/trace:0)
foo
