#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit
[[ -n "${VERBOSE:-}" ]] && set -o verbose

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
readonly SCRIPT_DIR
# shellcheck source=./init.bash
source "$SCRIPT_DIR"/init.bash

foo() {
  l.trace_stack foo
}

# It will print:
# Trace Function Stack:
#   # Function (File:Line)
#   - main (./example/trace:0)
l.trace_stack

# It will print:
# Trace Function Stack: foo
#   # Function (File:Line)
#   - foo (./example/trace:36)
#   - main (./example/trace:0)
foo
