#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit
[[ -n "${VERBOSE:+x}" ]] && set -o verbose
[[ -n "${DEBUG:-}" ]] && IS_DEBUG=true || IS_DEBUG=false

readonly SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
# shellcheck source=./init.bash
source "$SCRIPT_DIR"/init.bash

a=$(echo '  123  ' | l.trim.p)
b=$(l.trim ' abcd ')

echo "a=$a and a.length=${#a}"
echo "b=$b and b.length=${#b}"
