#!/usr/bin/env bash
# shellcheck disable=SC1090

set -o errexit
set -o nounset
set -o pipefail
[[ -n "${XTRACE:+x}" ]] && set -o xtrace
[[ -n "${VERBOSE:+x}" ]] && set -o verbose
[[ -n "${DEBUG:-}" ]] && IS_DEBUG=true || IS_DEBUG=false
[[ $- =~ [x] ]] && PS4='+[${BASH_SOURCE}:${LINENO}:${FUNCNAME[0]:+${FUNCNAME[0]}}()]: '

export IS_LOBASH_TEST=1
LOBASH_ROOT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
export LOBASH_ROOT_DIR
export LOBASH_TEST_DIR=$LOBASH_ROOT_DIR/test

setup_fixture() {
  source "$LOBASH_TEST_DIR"/fixture/setup.bash
}
export -f setup_fixture

if [[ ${1:-} == '-d' ]]; then
  shift
  load_module() {
    source "$LOBASH_ROOT_DIR/dist/lobash.bash"
  }
fi

test_dirs=${1:-}

if [ -z "$test_dirs" ]; then
  test_dirs=( "$LOBASH_TEST_DIR"/{,modules} )
else
  test_dirs=( "$1" )
fi

exec bats ${CI:+--tap} "${test_dirs[@]}"
