#!/usr/bin/env bash

set -o errexit -o nounset -o pipefail -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

export IS_LOBASH_TEST=1
LOBASH_ROOT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
export LOBASH_ROOT_DIR
export LOBASH_TEST_DIR=$LOBASH_ROOT_DIR/tests
export LOBASH_USE_DIST

setup_fixture() {
  # shellcheck source=./tests/fixture/setup.bash
  source "$LOBASH_TEST_DIR"/fixture/setup.bash
}
export -f setup_fixture

if [[ ${1:-} == '-d' ]]; then
  shift

  if [[ ! -f "$LOBASH_ROOT_DIR/dist/lobash.bash" ]]; then
    echo "Not found $LOBASH_ROOT_DIR/dist/lobash.bash" >&2
    exit 2
  fi

  LOBASH_USE_DIST=true
elif [[ "${*: -1}" == -d ]]; then
  set -- "${@:1:$#-1}"

  if [[ ! -f "$LOBASH_ROOT_DIR/dist/lobash.bash" ]]; then
    echo "Not found $LOBASH_ROOT_DIR/dist/lobash.bash" >&2
    exit 2
  fi

  LOBASH_USE_DIST=true
fi

declare -a bats_args=(
  --print-output-on-failure
)

if [[ -n ${CI:-} ]]; then
  bats_args+=(--tap)
fi

if [[ ${1:-} == '-j' ]] && [[ -n ${2:-} ]]; then
  bats_args+=(-j "$2")
  shift 2
fi

if [[ -z "${1:-}" ]]; then
  test_dirs=("$LOBASH_TEST_DIR"/{,modules})
else
  test_dirs=("$1")
fi

export PATH="$LOBASH_TEST_DIR/fixture/bats/bin:${PATH}"
bats --version

exec bats "${bats_args[@]}" "${test_dirs[@]}"
