#!/usr/bin/env bash
# Supported Bash: 4.0+

set -o errexit
set -o nounset
set -o pipefail
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit
[[ -n "${VERBOSE:-}" ]] && set -o verbose
[[ -n "${DEBUG:-}" ]] && IS_DEBUG=true || IS_DEBUG=false

export IS_LOBASH_TEST=1
LOBASH_ROOT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
export LOBASH_ROOT_DIR
export LOBASH_TEST_DIR=$LOBASH_ROOT_DIR/tests

setup_fixture() {
  # shellcheck source=./tests/fixture/setup.bash
  source "$LOBASH_TEST_DIR"/fixture/setup.bash
}
export -f setup_fixture

if [[ ${1:-} == '-d' ]]; then
  shift
  load_module() {
    # shellcheck source=./dist/lobash.bash
    source "$LOBASH_ROOT_DIR/dist/lobash.bash"
  }
fi

if [[ -z "${1:-}" ]]; then
  test_dirs=( "$LOBASH_TEST_DIR"/{,modules} )
else
  test_dirs=( "$1" )
fi

export PATH="$LOBASH_TEST_DIR/fixture/bats/bin:${PATH}"

exec bats ${CI:+--tap} "${test_dirs[@]}"
