#!/usr/bin/env bash
# This script should support Bash: 4.0+

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit
[[ -n "${VERBOSE:-}" ]] && set -o verbose

export IS_LOBASH_TEST=1
LOBASH_ROOT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
export LOBASH_ROOT_DIR
export LOBASH_TEST_DIR=$LOBASH_ROOT_DIR/tests
export LOBASH_USE_DIST

setup_fixture() {
  # shellcheck source=./tests/fixture/setup.bash
  source "$LOBASH_TEST_DIR"/fixture/setup.bash
}
export -f setup_fixture

if [[ ${1:-} == '-d' ]]; then
  shift

  if [[ ! -f "$LOBASH_ROOT_DIR/dist/lobash.bash" ]]; then
    echo "Not found $LOBASH_ROOT_DIR/dist/lobash.bash" >&2
    exit 2
  fi

  LOBASH_USE_DIST=true
fi

if [[ -z "${1:-}" ]]; then
  test_dirs=( "$LOBASH_TEST_DIR"/{,modules} )
else
  test_dirs=( "$1" )
fi

export PATH="$LOBASH_TEST_DIR/fixture/bats/bin:${PATH}"

exec bats ${CI:+--tap} "${test_dirs[@]}"
