#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

readonly SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"

main() {
  local version="${BASHVER:-4.4}"
  export VERSION="$version"

  local docker_args=(
    -t "lobash/test-bash:$version"
  )

  if [[ -n ${IN_CHINA:-} ]]; then
    docker_args+=(
      --build-arg APK_PROXY=true
      --build-arg GH_PROXY=https://ghproxy.com/
    )
  fi

  envsubst < "$SCRIPT_DIR"/test.dockerfile | docker build "$@" "${docker_args[@]}" -
}

main "$@"
