#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit
[[ -n "${VERBOSE:-}" ]] && set -o verbose

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
readonly SCRIPT_DIR

main() {
  local version="${BASHVER:-4.4}"

  local docker_args=(
    -t "lobash/test-bash:$version"
    --build-arg "VERSION=$version"
  )

  if [[ -n ${IN_CHINA:-} ]]; then
    docker_args+=(
      --build-arg 'APK_PROXY=mirrors.ustc.edu.cn'
      --build-arg 'GH_PROXY=https://ghproxy.com/'
    )
  fi

  docker build "$@" "${docker_args[@]}" - < "$SCRIPT_DIR"/test.dockerfile
}

main "$@"
