#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
readonly SCRIPT_DIR

# shellcheck source=./test-image-versions
source "$SCRIPT_DIR/test-image-versions"

main() {
  for version in "${TEST_IMAGE_VERIONS[@]}"; do
    IN_CHINA=${IN_CHINA:-} BASHVER=$version "$SCRIPT_DIR/build-test-image" "$@"
  done
}

main "$@"
