#!/usr/bin/env bash
# shellcheck disable=SC1090

set -o errexit
set -o nounset
set -o pipefail
shopt -s inherit_errexit
[[ -n "${VERBOSE:+x}" ]] && set -o verbose
[[ -n "${DEBUG:-}" ]] && IS_DEBUG=true || IS_DEBUG=false

readonly SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"

main() {
  local version="${ZSHVER:-5.3}"
  export VERSION="$version"
  envsubst < "$SCRIPT_DIR"/test.zsh.dockerfile | docker build "$@" -t lobash/test-zsh:"$version" -
}

main "$@"
