#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

if (( $# == 0)) || [[ $1 == -h ]] || [[ $1 == --help ]]; then
  cat <<EOF
Usage: $0 <major|minor|patch>
Description: bump version for release
EOF
  exit 0
fi

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
readonly SCRIPT_DIR

semver=$SCRIPT_DIR/../tmp/semver

ensure_semver() {
  if [[ ! -f $semver ]]; then
    echo "To download semver-tool"
    curl -Lo "$semver" https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
    chmod +x "$semver"
  fi
}

main() {
  ensure_semver

  local version_file="$SCRIPT_DIR/../version"
  local cur_ver next_ver
  cur_ver=$(cat "$version_file")
  next_ver=$( "$semver" bump "$1" "$cur_ver" )
  echo "$next_ver" > "$version_file"
  echo "bump version: $cur_ver -> $next_ver"
}

main "$@"
