#!/usr/bin/env bash
# shellcheck disable=SC1090

set -o errexit
set -o nounset
set -o pipefail
[[ -n "${XTRACE:+x}" ]] && set -o xtrace
[[ -n "${VERBOSE:+x}" ]] && set -o verbose
[[ -n "${DEBUG:-}" ]] && IS_DEBUG=true || IS_DEBUG=false
[[ $- =~ [x] ]] && PS4='+[${BASH_SOURCE[0]}:${LINENO}|${FUNCNAME[0]:+${FUNCNAME[0]}}()|$?]: '

readonly SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"

source "$SCRIPT_DIR"/../src/import.bash

import upper_case normalize

warn() {
  printf '[%s] %s\n' "$(l.upper_case "${FUNCNAME[1]}")" "$*" >&2
}

error() { warn "$@"; }

check_file() {
  if [[ ! -f $1 ]]; then
    error not found module file: "$1"
    return 3
  fi

  local filename extension
  filename=$(basename "$1")
  extension="${filename##*.}"

  if [[ $filename == bash ]] || [[ $extension != bash ]]; then
    error Module file extension must be .bash
    return 3
  fi

  if [[ $filename =~ - ]]; then
    error Module file name cannot contain \"-\"
    return 3
  fi

  if [[ $filename =~ [-_.]$ ]]; then
    error Module file name cannot ends with \"-\" or \"_\" or \".\"
    return 3
  fi
}

check_no_export() {
  local filepath=$1
  local found
  found=$(grep 'export ' "$filepath" || true)
  if [[ -n $found ]]; then
    error "'export' variable and function is forbidden."
    error "Matched text: $found"
    return 3
  fi
}

check_lodash_typos() {
  local filepath=$1
  local found
  found=$(grep '[lL][oO][dD][aA][sS][hH]' "$filepath" || true)
  if [[ -n $found ]]; then
    warn Found word \"lodash\". Is it a typo? Please check your code.
    warn Matched text: "$found"
    return 3
  fi
}

check_alias() {
  local found
  found="$(grep '^alias ' "$1" || true)"

  if [[ -n "$found" ]]; then
    error alias is forbidden
    return 3
  fi
}

check_pubilc_function() {
  local count found
  found="$(grep -E '^([A-Za-z0-9]\w*)\(\) ?\{$' "$1")"
  count=$(wc -l <<< "$found")
  count=${count// /}

  if [[ $count -ne 1 ]]; then
    error Each module must define one public function.
    error Found "'${count}'" public functions:
    error "${found// \{/}"
    return 3
  fi
}

check_metadata() {
  local lines found
  found=$(sed -n '/^# ---$/,/^# ---$/p' "$1")
  lines=$( wc -l <<< "$found" )
  lines=${lines// /}

  if [[ $lines -lt 3 ]]; then
    error Module metadata is empty.
    return 3
  fi
}

check_no_echo() {
  local filepath=$1

  if grep -o ' echo ' "$filepath" >/dev/null; then
    echo 'Use printf instead of echo.'
    return 3
  fi
}

check_duplicated_function() {
  local filepath=$1
}

check_module() {
  local filepath=$1
  filepath=$(l.normalize "$filepath")

  rules=(
  check_file
  check_alias
  check_pubilc_function
  check_metadata
  check_lodash_typos
  check_no_export
  # check_no_echo
  check_duplicated_function
  )

  for i in "${!rules[@]}"; do
    local rule_name=${rules[$i]}
    $rule_name "$filepath" || error "[$filepath][Rule: $rule_name]"
  done
}

check_all_module() {
  for filepath in $SCRIPT_DIR/../src/modules/*.bash; do
    check_module "$filepath"
  done
}

main() {
  if [[ $1 == all ]]; then
    check_all_module
  else
    check_module "$1"
  fi
}

main "$@"
