#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit
[[ -n "${VERBOSE:+x}" ]] && set -o verbose
[[ -n "${DEBUG:-}" ]] && IS_DEBUG=true || IS_DEBUG=false

readonly SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"

# echo "[Todo] $SCRIPT_DIR/gen-categories"
# "$SCRIPT_DIR"/gen-categories
"$SCRIPT_DIR"/gen-module-docs
"$SCRIPT_DIR"/gen-configs
