#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit
[[ -n "${VERBOSE:-}" ]] && set -o verbose

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
readonly SCRIPT_DIR

"$SCRIPT_DIR"/gen-categories
"$SCRIPT_DIR"/gen-module-docs
"$SCRIPT_DIR"/gen-configs
