#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit
[[ -n "${VERBOSE:-}" ]] && set -o verbose

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
readonly SCRIPT_DIR

# shellcheck source=./colors.bash
source "$SCRIPT_DIR/colors.bash"
# shellcheck source=../src/load_internals.bash
source "$SCRIPT_DIR"/../src/load_internals.bash
_lobash.import_internals basic_meta_types module_meta rm erase_line
_lobash.imports array_include

get_metas() {
  local name=$1
  local i
  while read -r i; do
    if [[ -n "$i" ]]; then
      printf '%s\n' "$i"
    fi
  done < <(echo "$metadatas" | grep -Eo "^${name}: .+$" | sed "s/${name}: //" || echo "${2:-}")
}

main() {
  echo "[Todo] generate categories"

  local CATE_DIR=$SCRIPT_DIR/../src/internals/categories
  _lobash.rm "$CATE_DIR"
  mkdir -p "$CATE_DIR"

  local filepath module_name category metadatas
  for filepath in $SCRIPT_DIR/../src/modules/*.bash; do
    module_name=$(basename "$filepath" .bash)

    metadatas=$(_lobash.get_module_metadata_str "$filepath")
    category=$(get_metas Category)

    if [[ -n $category ]]; then
      category=${category,,}
      _lobash.erase_line
      printf '%s' "Added to category: $category/$module_name"
      printf '%s\n' "$module_name" >> "$CATE_DIR/$category"
    fi
  done

  printf '\n%b\n' "${GREEN}Generated categories in directory: $CATE_DIR${RESET_ALL}"
}

main
