#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit
[[ -n "${VERBOSE:-}" ]] && set -o verbose

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
readonly SCRIPT_DIR

# GNU Mirror List: https://www.gnu.org/prep/ftp.html
MIRROR=https://gnu.freemirror.org
VERSION=$1
TRAVIS_BUILD_DIR=${TRAVIS_BUILD_DIR:-"$SCRIPT_DIR/../dist"}
BUILD_DIR=${TRAVIS_BUILD_DIR}/build-bash/$VERSION

mkdir -p "$BUILD_DIR"
cd "$TRAVIS_BUILD_DIR"

if [[ ! -f bash-"$VERSION".tar.gz ]]; then
  curl -k -O $MIRROR/gnu/bash/bash-"$VERSION".tar.gz
fi

tar xzf bash-"$VERSION".tar.gz
cd "bash-$VERSION"
./configure --prefix="$BUILD_DIR"
make
make install
