#!/usr/bin/env bash
# shellcheck disable=SC2016

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit
[[ -n "${VERBOSE:-}" ]] && set -o verbose

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
readonly SCRIPT_DIR

if (( $# == 0 )); then
  cat <<EOF
Usage: $0 <module-name>
Description: Print metadatas of module
EOF
  exit 0
fi

# shellcheck source=./colors.bash
source "$SCRIPT_DIR/colors.bash"
# shellcheck source=../src/load_internals.bash
source "$SCRIPT_DIR/../src/load_internals.bash"

_lobash.import_internals basic_meta_types module_meta erase_line rm
_lobash.imports sort has

# shellcheck source=./module-meta.bash
source "$SCRIPT_DIR/module-meta.bash"

function main() {
  local module_name=$1
  local filepath=$SCRIPT_DIR/../src/modules/$module_name.bash

  if [[ ! -f $filepath ]]; then
    echo "Not found module '$module_name'" >&2
    return 1
  fi

  local metadatas
  metadatas=$(_lobash.get_module_metadata_str "$filepath")
  _lobash.scan_module_metadata "$module_name"

  TARGET=/dev/stdout
  print_module_metas "$module_name"
}

main "$@"
