#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
readonly SCRIPT_DIR

echo "[run-in-docker] BASHVER=${BASHVER:=4.4}"
DOCKER_IMAGE="lobash/test-bash:$BASHVER"

args=(
  --rm -it
  -e DOCKER=true
  -e CI="${CI:-}"
  -e OS="alpine"
  -e BASHVER="$BASHVER"
)

vols=(
  .git test build version src tests tools
  dist example bin
)

for vol in "${vols[@]}"; do
  v=$(printf '%s:%s' "$SCRIPT_DIR/../$vol" "/lobash/$vol")
  # shellcheck disable=2016
  args+=( -v "$v")
done

echo "docker run ${args[*]} $DOCKER_IMAGE"

docker run "${args[@]}" "$DOCKER_IMAGE"
