#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
readonly SCRIPT_DIR

echo "[run-in-docker] BASHVER=${BASHVER:=4.4}"

docker run \
  --rm -it \
  -e DOCKER=true \
  -e CI="${CI:-}" \
  -e OS="alpine" \
  -e BASHVER=$BASHVER \
  -v "$SCRIPT_DIR"/../bin:/lobash/bin \
  -v "$SCRIPT_DIR"/../example:/lobash/example \
  -v "$SCRIPT_DIR"/../test:/lobash/test \
  -v "$SCRIPT_DIR"/../build:/lobash/build \
  -v "$SCRIPT_DIR"/../version:/lobash/version \
  -v "$SCRIPT_DIR"/../src:/lobash/src \
  -v "$SCRIPT_DIR"/../tests:/lobash/tests \
  -v "$SCRIPT_DIR"/../tools:/lobash/tools \
  -v "$SCRIPT_DIR"/../dist:/lobash/dist \
  lobash/test-bash:"${BASHVER}"
