#!/usr/bin/env bash
# shellcheck disable=SC1090

set -o errexit
set -o nounset
set -o pipefail
shopt -s inherit_errexit
[[ -n "${VERBOSE:+x}" ]] && set -o verbose
[[ -n "${DEBUG:-}" ]] && IS_DEBUG=true || IS_DEBUG=false

readonly SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"

echo "[test-zsh-in-docker] ZSHVER=${ZSHVER:=5.3}"

if [[ -z $(docker images -q lobash/test-zsh:"${ZSHVER}") ]]; then
  echo "To build image lobash/test-zsh:${ZSHVER}"
  ZSHVER=$ZSHVER "$SCRIPT_DIR/build-test-zsh-image"
fi

docker run \
  --rm -it \
  -e DOCKER=true \
  -e CI="${CI:-}" \
  -v "$SCRIPT_DIR"/../test:/lobash/test \
  -v "$SCRIPT_DIR"/../build:/lobash/build \
  -v "$SCRIPT_DIR"/../version:/lobash/version \
  -v "$SCRIPT_DIR"/../src:/lobash/src \
  -v "$SCRIPT_DIR"/../tests:/lobash/tests \
  -v "$SCRIPT_DIR"/../dist:/lobash/dist \
  lobash/test-zsh:"${ZSHVER}"
