#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
(shopt -p inherit_errexit &>/dev/null) && shopt -s inherit_errexit
[[ -n "${VERBOSE:-}" ]] && set -o verbose

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
readonly SCRIPT_DIR

BASH_BIN_PATH=$SCRIPT_DIR/../tmp/bash-$BASHVER/bin
if [[ ! -f $BASH_BIN_PATH/bash ]]; then
  echo "Not found $BASH_BIN_PATH/bash. To install Bash $BASHVER"
   BASHVER="$BASHVER" "$SCRIPT_DIR"/../tools/install-bash
fi

PATH=$BASH_BIN_PATH:$PATH

cmd=$SCRIPT_DIR/../test
if (( $# > 0 )); then
  bash "$cmd" "$@"
else
  bash "$cmd"
fi

