#!/usr/bin/env bash
# shellcheck disable=SC1090

set -o errexit
set -o nounset
set -o pipefail
[[ -n "${XTRACE:+x}" ]] && set -o xtrace
[[ -n "${VERBOSE:+x}" ]] && set -o verbose
[[ -n "${DEBUG:-}" ]] && IS_DEBUG=true || IS_DEBUG=false
[[ $- =~ [x] ]] && PS4='+[${BASH_SOURCE[0]}:${LINENO}|${FUNCNAME[0]:+${FUNCNAME[0]}}()|$?]: '

dir=$(pwd)

docker run \
  -v "$dir"/run_test:/lobash/run_test \
  -v "$dir"/src:/lobash/src \
  -v "$dir"/test:/lobash/test \
  bash:"${BASHVER:-4.4}" /lobash/run_test
