name: local-test

on: workflow_call

jobs:
  test:
    runs-on: macos-12
    steps:
      - run: LC_ALL=C tr -dc "a-zA-Z0-9@#*=[]" < /dev/urandom | head -c 10

  local:
    runs-on: macos-12
    strategy:
      fail-fast: true
      matrix:
        # BASHVER: ['4.0']  # bash 4.0 has bug on MacOS: pointer being freed was not allocated
        BASHVER: ['4.1']

    steps:
      - uses: actions/checkout@v3

      - name: Init
        run: |
          echo "PWD: $PWD"
          echo "ACT: ${{ env.ACT }}"

          git submodule update --init --recursive
          mkdir -p ./tmp

      - name: Download bash-${{ matrix.BASHVER }}.tar.gz
        if: steps.cache-bash.outputs.cache-hit != 'true'
        run: |
          curl --silent -L -o ./bash.tar.gz https://ftp.gnu.org/gnu/bash/bash-${{ matrix.BASHVER }}.tar.gz
          tar -xzf ./bash.tar.gz
        working-directory: tmp

      - name: Install bash
        if: steps.cache-bash-install.outputs.cache-hit != 'true'
        run: |
          CFLAGS='-Wno-implicit-function-declaration -DSSH_SOURCE_BASHRC' ./configure --silent
          make
          mkdir -p ${{ github.workspace }}/tmp/bash-install
          make install prefix=/ DESTDIR=${{ github.workspace }}/tmp/bash-install
        working-directory: tmp/bash-${{ matrix.BASHVER }}

      - name: To build ./dist/lobash.bash
        run: |
          export PATH="${{ github.workspace }}/tmp/bash-install/bin:$PATH"
          bash --version
          ./build -m "${{ matrix.BASHVER }}" ./dist/

          # docker run --rm -v "${{ github.workspace }}:/workspace" lobash/build:4.1 \
          #       '/workspace/build -m "${{ matrix.BASHVER }}" /workspace/dist/'

      - name: Start to test
        run: |
          export PATH="${{ github.workspace }}/tmp/bash-install/bin:$PATH"
          CI=true ./test -d
